return {
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    main = "nvim-treesitter.configs",
    lazy = true,
    event = "VeryLazy",
    opts = {
      auto_install = false,
      ensure_installed = {
        "apex",
        "bash",
        "html",
        "hyprlang",
        "javascript",
        "lua",
        "markdown",
        "markdown_inline",
        "python",
        "query",
        "rasi",
        "regex",
        "sflog",
        "soql",
        "sosl",
        "sql",
        "vim",
        "vimdoc",
        "xml",
      },
      highlight = { enable = true },
      indent = { enable = true },
    },
  },
  {
    "nvim-treesitter/nvim-treesitter-context",
    lazy = true,
    event = "VeryLazy",
  },
  {
    "HiPhish/rainbow-delimiters.nvim",
    main = "rainbow-delimiters.setup",
    lazy = true,
    event = "VeryLazy",
    config = true,
  },
}
